# Generated by Django 5.1.2 on 2024-11-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last',
            new_name='last_name',
        ),
    ]
