# Generated by Django 5.1.2 on 2024-11-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('register', '0002_rename_last_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(related_name='fav_books', to='register.user'),
        ),
    ]
